import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";
import Link from "next/link";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Lopilo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-bgColor1   overflow-x-hidden`}
      >
        <div className="text-center pt-4">
          <Link
            href="/admin"
            className="inline-block bg-blue-600 text-white font-semibold py-2 px-4 rounded transition-all duration-300 ease-in-out hover:bg-blue-500 hover:shadow-lg"
          >
            Dashboard
          </Link>
        </div>

        <main> {children} </main>

        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
